name: Coverage

# Runs whenever a push to main occurs.
on:
  push:
    branches: [main]
    
jobs:

  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.11'
    steps:
    - uses: checkout@v3
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: 3.11
    - name: Generate Report
      run: |
        python -m pip install -U pip
        pip install pytest
        pip install responses
        pip install -r requirements.txt
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
